reset;
option ampl_include 'C:\Users\Edielson\Documents\Researches\automatic-power-optimization\ampl';

option solver cplex;

model BackupModel.mod;
data BackupDataN4.dat;

option log_file 'C:\Users\Edielson\Documents\Researches\automatic-power-optimization\ampl\BackupLogN4.log';


let K := (max{(s,d) in LINKS} capacity_P[s,d])+1;

option cplex_options 'mipgap=0.01 mipdisplay=3';

solve;
display CB;
#display B;

option log_file '';